ariadne/app-qt/Glue.hs, ariadne/app-qt/Main.hs, ariadne/app/Glue.hs, ariadne/app/Main.hs, ariadne/ariadne.cabal, ariadne/src/Ariadne/UX/CommandHistory.hs, ui/qt/src/Ariadne/UI/Qt.hs, ui/qt/src/Ariadne/UI/Qt/Face.hs, ui/qt/src/Ariadne/UI/Qt/MainWindow.hs, ui/qt/src/Ariadne/UI/Qt/Widgets/Repl.hs, ui/vty/ariadne-vty-ui.cabal, ui/vty/src/Ariadne/UI/Vty.hs, ui/vty/src/Ariadne/UI/Vty/App.hs, ui/vty/src/Ariadne/UI/Vty/CommandHistory.hs, ui/vty/src/Ariadne/UI/Vty/Face.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Repl.hs
I extracted history file handling to `ariadne` and made both UIs use this common interface.
=> [AD-155] Add command history to GUI

Makefile
To build lib with logs printed.
=> Add dev-lib target to Makefile

ariadne/src/Ariadne/Wallet/Cardano/Kernel/Bip44.hs
It's needed to properly implement transaction sending where we need
to derive keys for all used addresses and we don't want to derive
account key more than once for each account. That's how current code
behaves and I want to preserve this behavior during AD-135 migration.
=> [AD-135] Add helpers for BIP-44 account path construction

ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Create.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Read.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/InDb.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/Word31.hs
These changes are from #194. They're quite standalone, simple and self-contained, so I decided to move it into a separate PR to make #194 a bit smaller and easier to review (it's very big currently).
=> [AD-135] Simple improvements necessary to use new backend

ariadne/src/Ariadne/UX/CommandHistory.hs
https://serokell.slack.com/archives/C9B1DAMDJ/p1530827626000335
=> [AD-259] Fix behavior when prefix does not exist in history

ariadne/src/Ariadne/Wallet/UiAdapter.hs, ui/qt/app/Glue.hs, ui/vty/app/Glue.hs
`UiWalletData` tree now have balances in all levels.
=> [AD-264] Add balance to tree in UiAdapter

ui/vty/src/Ariadne/UI/Vty/App.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Menu.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Repl.hs
Much disputable very don't merge wow
=> [AD-61] Make REPL widget omnipresent

ui/vty/app/Glue.hs, ui/vty/src/Ariadne/UI/Vty/App.hs, ui/vty/src/Ariadne/UI/Vty/Face.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Wallet.hs
Depends on #232, so it should be merged first
=> [AD-263] Show balances in list of addresses in account

ui/vty/app/Glue.hs
**YT issue:** https://issues.serokell.io/issue/AD-214
**Checklist:**
This was requested in #155.
=> [AD-214] Reduce code duplication in opToExpr in Glue

ui/vty/app/Glue.hs, ui/vty/src/Ariadne/UI/Vty/Face.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Form/Send.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-215
**Checklist:**
As per @gromakovsky's suggestion created data types for most `UiCommand` arguments.
Also, rearranged types in `Face.hs` and unified code style.
=> [AD-215] Cleanup Face.hs

.github/pull_request_template.md
**YT issue:** I dare to make a PR without corresponding YT issue.
**Checklist:**
Added one more thing to the PR template.
=> Add a checkmark about testing to the PR template

docs/usage-tui.md
**YT issue:** https://issues.serokell.io/issue/PRS-38
I've done some fixing of grammar mistakes and little rephrasing to make the guide clearer/more elegant.
=> [PRS-38] Edit Ariadne "Usage guide"

ui/qt/app/Glue.hs, ui/qt/src/Ariadne/UI/Qt/Face.hs, ui/qt/src/Ariadne/UI/Qt/MainWindow.hs, ui/qt/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/vty/app/Glue.hs, ui/vty/src/Ariadne/UI/Vty/Face.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Logs.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Status.hs
**YT issue:** https://issues.serokell.io/issue/AD-310
**Checklist:**
These events are useful for other cryptocurrencies, so they should be appropriately called.
=> [AD-310] Use more currency-agnostic names for backend events

ariadne/cardano/src/Ariadne/Config/Cardano.hs, ariadne/cardano/src/Ariadne/Config/DhallUtil.hs
**YT issue:** https://issues.serokell.io/issue/AD-enot
**Checklist:**
N.B. Ariadne.Config.Cardano imports Ariadne.Config.DhallUtil.
=> Move one of the imports to the place where it's actually needed

stack.yaml
**YT issue:** https://issues.serokell.io/issue/SRK-2
**Checklist:**
See https://github.com/jystic/unix-compat/pull/40.
=> Fix linking error on some systems

ariadne/cardano/src/Ariadne/Wallet/Knit.hs, ariadne/cardano/src/Ariadne/Wallet/UiAdapter.hs, ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-269
**Checklist:**
=> [AD-269] Show wallet ids in TUI

ui/vty-app/Main.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-357
**Checklist:**
Disabled for Cardano wallet, but utilized by Disciplina (see DisciplinaOU/disciplina#137)
=> [AD-357] Plaintext wallet key export

ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs
**YT issue:** https://issues.serokell.io/issue/AD-354
**Checklist:**
1. acid-state DB is now properly closed.
2. bracket* functions from wallet kernel have been replaced with functions
returning `ComponentM` to make it easier to use them with the rest of the
code.
3. `PassiveWalletLayer` is now created without hacks.
4. I wrapped tuple returned by `createWalletBackend` into a new ADT, because it looked a bit scary.
**Note**: #275 should be merged first!
=> [AD-354] Properly release resources

ariadne/cardano/src/Ariadne/Config/CLI.hs
**YT issue:** https://issues.serokell.io/issue/AD-350
**Checklist:**
Previously there was a small difference between using `config/ariadne-config.dhall` and using hardcoded config (which is used when config file can't be found), because relative paths in hardcoded config weren't treated as relative to 'configPath', while paths in
config file were.
Having two different default configs seems bad and confusing, so this difference was eliminated.
The only relative path in the default config is path to `cardano-configuration.yaml`. In default case the only difference for a user is that this file (and `mainnet-genesis.json`) will be dumped into `~/.config/ariadne/` instead of current directory, which is better, I think.
=> [AD-350] Make two defaults configs identical

.github/pull_request_template.md, README.md, docs/configuration.md
**YT issue:** https://issues.serokell.io/issue/AD-352
**Checklist:**
I've expanded documentation of configuration and moved it into a separate file (from README). Also updated pull request template.
=> [AD-352] Write documentation about configuration

ui/vty-app/Main.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/DSCP-220
**Checklist:**
=> [DSCP-220] Wallet tx history for Disciplina

stack.yaml, ui/qt-app/Glue.hs, ui/qt-lib/resources/stylesheet.qss, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/MainWindow.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/NewWallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletTree.hs
**YT issue:** https://issues.serokell.io/issue/AD-330
**Checklist:**
Added QComboBox with two options: create new wallet and import.
=> [AD-330] Implement wallet restore dialog

CODEOWNERS
Forgot to update them earlier, when I split UI packages.
=> Update UI codeowners

ui/vty-lib/src/Ariadne/UI/Vty/Scrolling.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/About.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Help.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Logs.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Tree.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-262
**Checklist:**
=> [AD-262] Add TUI viewport with scrollbar

ariadne/cardano/src/Ariadne/Config/Ariadne.hs, ariadne/cardano/src/Ariadne/Config/CLI.hs, ariadne/cardano/src/Ariadne/Config/Cardano.hs, ariadne/cardano/src/Ariadne/Config/History.hs, ariadne/cardano/test/Spec.hs, ariadne/cardano/test/Test/Ariadne/Cardano/Arbitrary.hs, config/cardano.dhall, config/history.dhall
**YT issue:** https://issues.serokell.io/issue/AD-364
**Checklist:**
Each commit is small and self-contained with a description of what's going on.
This whole PR is quite simple.
=> AD-364 Small fixes for configuration

ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Send.hs
**YT issue:** https://issues.serokell.io/issue/DSCP-233
**Checklist:**
As we have use the UI library in two different wallets, it must not have any hardcoded currency names.
=> [DSCP-233] Get rid of any currency mention in Vty UI

ui/qt-app/Glue.hs, ui/qt-lib/ariadne-qt-lib.cabal, ui/qt-lib/resources/stylesheet.qss, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Delete.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/NewWallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Util.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
**YT issue:** https://issues.serokell.io/issue/AD-331
**Checklist:**
=> [AD-331] Add dialog to remove wallet

ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, ui/cli-app/Main.hs, ui/qt-app/Glue.hs, ui/qt-app/Main.hs, ui/qt-app/ariadne-qt-app.cabal, ui/qt-lib/ariadne-qt-lib.cabal, ui/qt-lib/resources/stylesheet.qss, ui/qt-lib/src/Ariadne/UI/Qt.hs, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/MainWindow.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/ConfirmMnemonic.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Delete.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Util.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletTree.hs, ui/vty-app/Main.hs
**YT issue:** https://issues.serokell.io/issue/AD-334
**Checklist:**
A dialog to confirm mnemonic. Some questions are present.
=> [AD-334] Mnemonic confirmation dialog

ariadne/cardano/src/Ariadne/Config/CLI.hs
**YT issue:** https://issues.serokell.io/issue/AD-374
**Checklist:**
Default config puts everything into `@DATA`. So we create `@DATA` when it does not exist.
If another config is used, it's user's responsibility to create all needed directories.
=> [AD-374] Create @DATA if default config is used

ariadne/cardano/ariadne-cardano.cabal, ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Decrypt.hs, ariadne/core/ariadne-core.cabal, knit/knit.cabal, knit/src/Knit/Argument.hs, ui/cli-app/ariadne-cli-app.cabal, ui/cli-lib/ariadne-cli-lib.cabal, ui/qt-app/ariadne-qt-app.cabal, ui/qt-lib/ariadne-qt-lib.cabal, ui/qt-lib/src/Ariadne/UI/Qt/UI.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/vty-app/ariadne-vty-app.cabal, ui/vty-lib/ariadne-vty-lib.cabal, ui/vty-lib/src/Ariadne/UI/Vty/Scrolling.hs
Enable `-Weverything` with exceptions as described [here](https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3).
Note that this should be merged after #288.
=> Use -Weverything

ariadne/cardano/src/Ariadne/Config/TH.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/AddressDiscovery.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Delete.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec/Read.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec/Util.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs, knit/src/Knit/Prelude.hs, ui/cli-app/Main.hs, ui/qt-app/Main.hs, ui/qt-lib/src/Ariadne/UI/Qt.hs, ui/qt-lib/src/Ariadne/UI/Qt/MainWindow.hs, ui/qt-lib/src/Ariadne/UI/Qt/StyleSheet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Delete.hs, ui/vty-app/Main.hs, ui/vty-lib/src/Ariadne/UI/Vty/App.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Logs.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
Run `stylish-haskell` on the entire codebase. No semantics is affected.
=> stylish-haskell

Makefile, ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/PrefilterTx.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Types.hs, default.nix, stack.yaml
**YT issue:** https://issues.serokell.io/issue/AD-353
**Checklist:**
1. Fixed Haddock errors.
2. Added commands to `Makefile`.
3. Enabled Haddock on CI.
`cardano-sl` update brings these fixes: https://github.com/serokell/cardano-sl/pull/39
=> AD-353 Make CI build Haddock

stack.yaml
These lines no longer solve the problem they are supposed to solve.
Moreover, they even seem to **cause** it.
**YT issue:** :kot:
**Checklist:**
=> Remove legacy

CONTRIBUTING.md, README.md
I've updated README and CONTRIBUTING with regards to our issue tracker.
**YT issue:** https://issues.serokell.io/issue/OPS-501
**Checklist:**
=> [OPS-501] Update information about issue tracker

ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Send.hs
**YT issue:** https://issues.serokell.io/issue/AD-225
**Checklist:**
Only UI part is implemented here with a "not implemented" stub in Glue.
Required for DSCP-253.
=> [AD-225] Estimated transaction fee stub

stack.yaml, ui/qt-lib/src/Ariadne/UI/Qt/UI.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/ConfirmMnemonic.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Delete.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/NewWallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Request.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Util.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/TopBar.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
**Description:** All needed fixes were merged upstream.
**YT issue:** https://issues.serokell.io/issue/AD-358
**Checklist:**
=> [AD-358] Use Qtah master

README.md, stack.yaml
=> Add Nix build documentation

ariadne/cardano/src/Ariadne/Config/CLI.hs, ariadne/cardano/src/Ariadne/Config/History.hs, ariadne/cardano/src/Ariadne/Config/Update.hs, ariadne/cardano/test/Spec.hs, ariadne/cardano/test/Test/Ariadne/History/Arbitrary.hs, ariadne/cardano/test/Test/Ariadne/Update/Arbitrary.hs
**YT issue:** https://issues.serokell.io/issue/AD-175
**Checklist:**
Use the correct configuration for Updates and History in CLI
=> [AD-175] use the correct configuration for Updates and History in CLI

CONTRIBUTING.md, Makefile
Added a PHONY `Makefile` target which applies `lint.sh` script.
**YT issue:** :kot:
**Checklist:**
=> Add `lint` target to Makefile

ariadne/core/src/Ariadne/UIConfig.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Settings.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/About.hs
**Description:**AD-427 Add UIConfig
**YT issue:** https://issues.serokell.io/issue/AD-427
**Checklist:**
=> [AD-427] Add UIConfig

ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs
Make banner look prettier.
Disclaimer: I'm an amateur in ascii art, probably that stroke was intended, I just seemed to make banner look messier.
**Checklist:**
=> Remove extra stroke in banner

ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Bip32.hs, stack.yaml, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs
**Description:** Switch to named-0.2.0.0
**YT issue:** https://issues.serokell.io/issue/AD-403
**Checklist:**
=> [AD-403] Switch to named-0.2.0.0

.github/pull_request_template.md, docs/gui-architecture.md
**Description:** GUI architecture documentation for developers
**YT issue:** https://issues.serokell.io/issue/AD-391
**Checklist:**
=> [AD-391] GUI architecture documentation for developers

ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**Description:** Add TUI buttons to remove current wallet/account
**YT issue:** https://issues.serokell.io/issue/AD-447
**Checklist:**
=> [AD-447] Add TUI buttons to remove current wallet/account

ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs
**Description:** Update TUI banner
**YT issue:** https://issues.serokell.io/issue/AD-460
**Checklist:**
=> [AD-460] Update TUI banner

ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs
Remove unused function (`walletGetSelection`).
**YT issue:** https://issues.serokell.io/issue/AD-483
**Checklist:**
=> [AD-483] Remove 'walletGetSelection'

ariadne/cardano/src/Ariadne/Wallet/Backend/AddressDiscovery.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Mode.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Restore.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Bip32.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Derivation.hs
**YT issue:** https://issues.serokell.io/issue/AD-248
**Checklist:**
=> [AD-248] Make DerivationPath a newtype

ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Types.hs
**YT issue:** https://issues.serokell.io/issue/AD-490
**Checklist:**
=> [AD-490] Add getBalance logic to PassiveWalletLayer

acid-view/COPYING.md, acid-view/README.md, acid-view/app/Main.hs, acid-view/package.yaml, acid-view/src/AcidView.hs, acid-view/src/CmdParse.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, stack.yaml
Added utility that displays acid state DB with hdwallets (and can display it's previous states).
See readme with examples of using it.
**YT issue:** https://issues.serokell.io/issue/AD-382
**Checklist:**
=> [AD-382] Tool for viewing current content of acid-state

ui/vty-app/Glue.hs
**Description:** Remove obsolete TODO
**YT issue:** ~~https://issues.serokell.io/issue/AD-~~
**Checklist:**
=> Remove obsolete TODO

README.md
=> [OPS-538] Update README.md

ariadne/cardano/package.yaml, ariadne/cardano/src/Ariadne/Config/Wallet.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Keystore.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Keystore/Persistence.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Keystore/Types.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Keystore/Util.hs, ariadne/cardano/test/backend/Test/Spec/Keystore.hs, ariadne/core/package.yaml, ariadne/core/src/Ariadne/System/FileMode.hs
**YT issue:** https://issues.serokell.io/issue/AD-34
**Checklist:**
=> [AD-34] New keystore

stack.yaml
**Description:** Update `cardano-sl` version after its breaking change.
**YT issue:** https://issues.serokell.io/issue/AD-513
**Checklist:**
=> [AD-513] Update cardano-sl version

.github/pull_request_template.md, CODEOWNERS, CONTRIBUTING.md, README.md
As result of DOC-10 we have development guidelines which include guidelines about [repository maintenance](https://www.notion.so/serokell/How-to-create-and-maintain-a-repository-9028c5c379364407b8b2019b69d2e64a).
I've updated some files accordingly. For more details see commit messages.
**YT issue:** https://issues.serokell.io/issue/AD-509
**Checklist:**
=> [AD-509] Update repository according to new guidelines 

README.md
Problem: by default Buildkite CI badge shows the status of the last build.
It can be a WIP branch where CI fails. It makes more sense to display build
status of the stable integration branch instead.
Solution: update the link to the badge.
https://issues.serokell.io/issue/AD-509
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
=> [AD-509] Limit CI build badge to the master branch

shell-native.nix
Fixup to https://github.com/serokell/ariadne/pull/399.
=> [AD-527] Clean up LOCALE_ARCHIVE assignment

ariadne/cardano/package.yaml, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Util.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection/FromGeneric.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection/Generic.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection/Generic/Fees.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection/Generic/Grouped.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection/Generic/LargestFirst.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/CoinSelection/Generic/Random.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/FeeEstimate.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Types.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, ariadne/cardano/src/Ariadne/Wallet/Knit.hs, ariadne/cardano/test/backend/Test/Infrastructure/Generator.hs, ariadne/cardano/test/backend/Test/Infrastructure/Genesis.hs, ariadne/cardano/test/backend/Test/Spec/Fee.hs, ariadne/cardano/test/backend/WalletUnitTest.hs, stack.yaml, ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Send.hs
**Description:** Fetch fee estimations from Cardano backend
**YT issue:** https://issues.serokell.io/issue/AD-397
**Checklist:**
=> [AD-397] Fetch fee estimations from Cardano backend

stack.yaml
Problem: during AD-397 development cardano-sl's version was updated
to point to the `binary-update` branch. The corresponding cardano-sl PR¹
had to be merged before merging ariadne's PR, but it was forgotten
accidentally.
Solution: merge PR¹ and update cardano-sl version in stack.yaml to the HEAD
of the `ariadne` branch.
¹ https://github.com/serokell/cardano-sl/pull/45
https://issues.serokell.io/issue/AD-397
- Tests
- Haddock
of Public …
=> [AD-397] Update cardano-sl version

ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Addresses.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Create.hs
- Create HdAddress internally within createAddress in Ariadne.Wallet.Cardano.Kernel.DB.AcidState
- Split createAccPrefiltered into 2 functions one of which is createAddrPrefiltered
- Move Creation logic from Ariadne.Wallet.Cardano.Kernel.DB.AcidState to  Ariadne.Wallet.Cardano.Kernel.DB.HdWallet.Create
https://issues.serokell.io/issue/AD-258
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a …
=> [AD-258] Create HdAddress internally within createAddress
