serokell/ariadne

stack.yaml, ui/qt/src/Ariadne/UI/Qt/Widgets/Repl.hs
qtah upstream merged our local changes and did a new release,
so we are using it now.
QCursor class was mapped properly by upstream, so our code had to be
fixed.
=> Update qtah to 0.5.0, fix QCursor usage

ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Create.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Read.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec/Update.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs
There are a few disputable decisions made here, please review with care.
* Account checkpoints remain in place, only the type `Checkpoint` is renamed to `AccCheckpoint`.
* Address checkpoints are added. They contain address balance.
* All state-modifying functions (`applyBlock`, `newPending`, `switchToFork`) are now generalized to work on `UpdatableWalletState`. There are two instances of it (both are stubbed with `error`): one for `AccCheckpoints` and the other for `AddrCheckpoints`.
=> [AD-118] Add address checkpoints

ariadne/src/Ariadne/Cardano/Knit.hs, knit/test/Spec.hs
Some commands (bvd-read, bvm, softwork-rule, ...) are not used and can
not be used in current Ariadne. When they are needed again, this commit
can be reverted.
=> [AD-228] Remove unusued commands

ariadne/src/Ariadne/Config/CLI.hs
`putText` has different semantics: it doesn't print newline character anymore.
`putStrLn` does print newline character.
=> Hotfix universum bump

ariadne/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/src/Ariadne/Wallet/Face.hs, ariadne/src/Ariadne/Wallet/Knit.hs, docs/usage-tui.md
Only interface is provided, because it's needed for UI.
It will be implemented a bit later, after we finally start using
the new backend.
=> [AD-233] Add "account" arguments to the 'send' command

default.nix
For unknown reason (probably accidentally) tests stopped being built and launched in #137. This PR fixes it.
=> [AD-239] Enable ariadne tests

ariadne/ariadne.cabal, knit/knit.cabal, ui/qt/ariadne-qt.cabal, ui/vty/ariadne-vty.cabal
This will be enabled by default in GHC 8.6, let's make our code ready for it
right now.
For more information see https://prime.haskell.org/wiki/Libraries/Proposals/MonadFail:
> Add a language extension -XMonadFailDesugaring that changes desugaring to
use MonadFail(fail) instead of Monad(fail) This has the effect that
typechecking will infer a MonadFail constraint for do blocks with failable
patterns, just as it is planned to do when the entire thing is done.
=> Enable MonadFailDesugaring everywhere

docs/usage-tui.md, ui/vty/src/Ariadne/UI/Vty/Keyboard.hs, ui/vty/src/Ariadne/UI/Vty/Scrolling.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Tree.hs
Up and Down now scroll through all items, old behavior is preserved in
Ctrl-Up and Ctrl-Down.
---
There are two disputable decisions in this PR:
- I made `KeyUp` and `KeyDown` events fire only when no modifier is presed. Previously REPL, for example, would treat Up and Ctrl-Up the same way, now it will react only to Up. Is that OK?
- I changed `j` and `k` to work like new Up and Down, not like new Ctrl-Up and Ctrl-Down (the old behavior).
=> [AD-222] Change arrow keys behavior in Tree

ariadne/ariadne.cabal, ariadne/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/Bip44.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/Decrypt.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/PrefilterTx.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/Word31.hs
* Introduce `Word31`, a custom type similar to `Coin`, that has `maxBound = 2^31-1`. It lives in `Ariadne.Wallet.Cardano.Kernel.Word31`.
* Put all BIP-44-related conversion into a separate module (`Ariadne.Wallet.Cardano.Kernel.Bip44`) and only expose the necessary stuff outside.
* Modify the rest of the code to comply with the refactoring.
=> [AD-219] Introduce BIP-44 helpers

ariadne/ariadne.cabal, ariadne/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/Bip32.hs
1. Part of BIP-32 logic was moved from KeyStorage.hs to a new module,
so that it logic can be easier used from other places.
2. Previously there was a function to derive a key by path and construct
an address (all at once). I split it into two functions basically.
=> [AD-135] Make BIP-32 functions more granular and reusable

ariadne/src/Ariadne/Wallet/Backend/KeyStorage.hs, ui/vty/app/Glue.hs, ui/vty/src/Ariadne/UI/Vty/App.hs, ui/vty/src/Ariadne/UI/Vty/Face.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Account.hs
Now wallet tree displays only two levels: wallets and accounts. Wallet
pane displays all addresses for the selected account. A possibility to
select an address is removed.
=> [AD-245] Remove addresses from the tree

knit/src/Knit/Core.hs
Specify bounds for number types more explicitly:
Word8 -> 8-bit UInt.
---
I did not touch `Int` as bounds for it are not fixed in Haskell, according to docs:
> A fixed-precision integer type with at least the range [-2^29 .. 2^29-1].
Also, I capitalized `UInt` to match our other types.
=> [AD-132] Rename number types in help

ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec/Update.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/PrefilterTx.hs
**YT issue:** https://issues.serokell.io/issue/AD-179
**Checklist:**
There are multiple essential changes in this PR:
1. `PrefilteredBlock` is now more structured. Previously there used to be just `Set TxIn` and `Utxo`; now the same things are stored in maps indexed by `AddrWithId`.
2. The stuff in `AcidState.hs` now passes around a function that narrows down a `PrefilteredBlock` or `PrefilteredUtxo` to just one address. It's named `narrowP` in `createPrefiltered`.
3. All of the former allows to implement `applyBlock` for address checkpoints. It reuses the exact same code as account checkpoints, but takes as input only the data that is relevant to the address that is being processed ("data" meaning `TxIn`s referring to spendings from this address and new utxo belonging to …
=> [AD-179] applyBlock for address checkpoints

ui/vty/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-288
**Checklist:**
Show account names instead of wallet name to fix this bug: https://i.imgur.com/XtOyL4t.png
=> [AD-288] Fix account names in Wallet widget

ariadne/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet.hs, ariadne/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs
**YT issue:** https://issues.serokell.io/issue/AD-233
**Checklist:**
This PR finishes AD-233. Earlier I added an argument with list of accounts to be used as inputs, but this argument was ignored.
Didn't test yet, will do. **Upd**: tested, seems to work.
=> [AD-233] Consider accounts argument in 'sendTx'

ui/vty/src/Ariadne/UI/Vty/App.hs, ui/vty/src/Ariadne/UI/Vty/Widget.hs
**YT issue:** https://issues.serokell.io/issue/AD-281
**Checklist:**
Don't go up the widget hierarchy if clicked widget is the direct ancestor of currently focused widget.
Accidental clicks outside input won't reset focus to first input in a form anymore.
=> [AD-281] Don't reset focus to first form input when clicking outside input

ui/vty/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-280
**Checklist:**
`Wallet`/`Account` widgets now have dynamic focus list too.
`updateFocusList` signature is still quite unfortunate, but I'm not ready for another refactoring yet :D
=> [AD-280] Exclude empty account/address lists from focus ring

Makefile
Various improvements to Makefile:
1. Added forgotten target to .PHONY.
2. Added comments.
3. `make dev` now also builds tests and benchmarks, I find it good,
because when I use `make dev` I normally want to check that *everything*
compiles.
4. `dev-vty` and `dev-qt` pass only one target to `stack build`, so there
will be some logs while build is going on.
=> [AD-301] Update Makefile

ariadne/src/Ariadne/Cardano/Knit.hs, ui/qt/app/Glue.hs, ui/vty/app/Glue.hs
**YT issue:** https://issues.serokell.io/issue/AD-295
**Checklist:**
Added `data Currency` for units (ADA / Lovelace) to avoid dealing with
strings. This is needed in GUI to select currency icon.
=> [AD-295] Improve Knit.showCoin

ui/vty/src/Ariadne/UI/Vty/Widget.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Form/Send.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Tree.hs, ui/vty/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-282
**Checklist:**
Previously we manually used `Brick.visible` for currently focused widgets, and these "visibility requests" prevented viewports to be scrolled past these focused widgets.
Now we automatically apply `Brick.visible` on focused widgets, _except_ when `widgetIgnoreVisibility` flag is set.
This flag is set every time user scrolls viewport using mouse or `PgUp`/`PgDn`/etc buttons, and reset after every other user interaction, so that the focused widget becomes visible again.
This behaviour is automatic for all concerned widgets, except `Tree`, which is being rendered manually.
=> [AD-282] Allow scrolling viewport past focused widget

ui/qt/app/Glue.hs, ui/qt/src/Ariadne/UI/Qt/Face.hs, ui/qt/src/Ariadne/UI/Qt/MainWindow.hs, ui/qt/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/qt/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
**YT issue:** https://issues.serokell.io/issue/AD-295
**Checklist:**
Backend now sends cached balance for each wallet and account, no need to
recalculate it on every selection change.
=> [AD-295] Use cached balances in GUI

ariadne/cardano/ariadne-cardano.cabal, ariadne/cardano/src/Ariadne/Cardano/Backend.hs, ariadne/cardano/src/Ariadne/Cardano/Face.hs, ariadne/cardano/src/Ariadne/Config/Ariadne.hs, ariadne/cardano/src/Ariadne/Config/CLI.hs, ariadne/cardano/src/Ariadne/Config/Cardano.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Word31.hs, ariadne/cardano/test/Spec.hs, ariadne/cardano/test/Test/Ariadne/Cardano/Arbitrary.hs, ariadne/core/ariadne-core.cabal, config/cardano.dhall, default.nix
**YT issue:** https://issues.serokell.io/issue/AD-328
**Checklist:**
Some configurable fields are very unlikely to be of interest for anybody, so we remove the ability to configure them to simplify code.
`AriadneConfig` was a `newtype` over `cardano-sl`'s `CommonNodeArgs`, now it's not. The reasons are:
1. Some fields are out of interest.
2. Flat structure is easier to work with.
3. Some other modifications will be necessary for AD-205 most likely.
Also I allowed myself to remove `unused-top-binds` suppression from `.cabal` files, to make it easier to remove stuff that it no longer needed (it was a problem for me while I was working on this issue).
=> [AD-328] Decrease number of configurable fields in CLI

ariadne/cardano/src/Ariadne/Cardano/Backend.hs, ariadne/cardano/src/Ariadne/Config/Cardano.hs, stack.yaml
**YT issue:** https://issues.serokell.io/issue/AD-336
**Checklist:**
_Prehistory_
If `--config` option (which defaults to `xdgConfigPath </> "ariadne-config.dhall"`) points to a non-existing file, the default configuration will be used. It can happen for users who built `ariadne` from source, launched it, but didn't copy/symlink configuration into default location. The default configuration uses filepaths like `"config/cardano/topology.yaml"`. That's not ideal because these files might not exist (it will most likely happen if someone launches `ariadne` not from the root of the repository). Ideally we want `ariadne` to be usable regardless of presence of any configuration files on disk.
There are three configuration files which Cardano uses. One of them is mandatory …
=> [AD-336] Permit static values for Configuration, LogConfig, Topology

ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel.hs
**YT issue:** https://issues.serokell.io/issue/AD-349
**Checklist:**
If `blocksByAccount` is empty, `ApplyBlock` will not do anything.
However, these events will be in the DB log of events. We don't want
to store useless events.
=> [AD-349] Do 'ApplyBlock' update only if it can change something

ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-355
**Checklist:**
Send tx and new account forms got cleared on success before, now add/restore wallet forms do that too.
=> [AD-355] Clear create/restore wallet form on success

ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-356
**Checklist:**
Previously, results of actions were retained during switching between wallets/accounts.
=> [AD-356] Clear request results when switching between wallets/accounts

ariadne/cardano/ariadne-cardano.cabal, ariadne/cardano/src/Ariadne/Cardano/Backend.hs, ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/core/ariadne-core.cabal, ariadne/core/src/Ariadne/Knit/Backend.hs, ariadne/core/src/Ariadne/TaskManager/Backend.hs, ariadne/core/src/Ariadne/UX/CommandHistory.hs, stack.yaml, ui/cli-app/Main.hs, ui/cli-app/ariadne-cli-app.cabal, ui/cli-lib/ariadne-cli-lib.cabal, ui/cli-lib/src/Ariadne/UI/Cli.hs, ui/qt-app/Main.hs, ui/qt-app/ariadne-qt-app.cabal, ui/qt-lib/ariadne-qt-lib.cabal, ui/qt-lib/src/Ariadne/UI/Qt.hs, ui/vty-app/Main.hs, ui/vty-app/ariadne-vty-app.cabal, ui/vty-lib/ariadne-vty-lib.cabal, ui/vty-lib/src/Ariadne/UI/Vty.hs
**YT issue:** https://issues.serokell.io/issue/AD-229
**Checklist:**
`componentm` has some generally useful features, but the main reason
for us to use it is that it should make it much easier to use `bracket`
style initialization of components. However, this commit doesn't add
cleanup actions, it only refactors existing code. Cleanup actions will
be added later. So only `buildComponent_` is used now, but `buildComponent`
will also be used.
Common functionality from `Main.hs` modules was moved into a new module called
`MainTemplate` because I didn't want to make the same changes in three places.
=> [AD-229] Use componentm for components creation

ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Delete.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs
**YT issue:** https://issues.serokell.io/issue/AD-273
**Checklist:**
For example, in case of wallet's deletion, accounts and addresses will be also deleted.
Deleteing of the whole subtree happens atomically.
I use "deleteIxAll" function to delete unused addresses and accouns directly.
But this function des nothing if the key is not presented in IxSet (invalid HdRootId/HdAccountId),
that is why i check it in the beginning and throw exception in case of invalid id.
=> [AD-273] Delete whole subtree when something is deleted.

.gitignore, ariadne/cardano/src/Ariadne/Config/Wallet.hs, ariadne/cardano/test/Spec.hs, config/wallet.dhall
Rename `.wallet-db` to `wallet-db` since this directory is now in XDG data dir, where there is no point in hiding it.
Please note that #288 should be merged first.
=> Rename .wallet-db to wallet-db

ui/qt-app/package.yaml
Apparently, YAML can't into merging lists, so the override in `package.yaml` replaces the one in exec-common.
Thus, I did a horrible act of copy-pasting ghc-options. :(
**Checklist:**
=> Fix ghc-options for ariadne-qt-app.cabal

ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Tree.hs
**YT issue:** https://issues.serokell.io/issue/AD-377
**Checklist:**
Remove read-only commands (`select`) in TUI from the `Repl` and the history, when launched by the UI.
=> [AD-377] mute read-only knit commands

ui/vty-lib/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
**YT issue:** https://issues.serokell.io/issue/AD-377
**Checklist:**
Disciplina wallet uses balance and tx history commands in Wallet widget and they should be muted too.
=> [AD-377] Mute balance and tx history commands as well

ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, stack.yaml, ui/qt-app/Glue.hs, ui/qt-app/Main.hs, ui/qt-lib/package.yaml, ui/qt-lib/resources/stylesheet.qss, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Send.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Util.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
**Description:** A dialog to send transaction. There are some questions to discuss.
qtah commit was updated to include QEvent::Type PlatformSurface value.
Without this generic QEvent handler fails with `toEnum` error.
**YT issue:** https://issues.serokell.io/issue/AD-279
**Checklist:**
=> [AD-279] Add Send dialog

ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Wallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
**Description:** When backend sends WalletUpdateEvent with emtpy selection, clear
WaletInfo widget as well. Otherwise after deleting current wallet the
widget contains stale info.
Clearing WalletInfo widget is the easiest way to achieve this, but I'm not 100% sure the best. Is there a case when backend sends empty selection info, but UI **must not** clear wallet pane?
**YT issue:** https://issues.serokell.io/issue/AD-394
**Checklist:**
=> [AD-394] Clear wallet pane when nothing selected

ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Send.hs
**Description:** Backend can select accounts automatically when none are selected by the
user.
**YT issue:** https://issues.serokell.io/issue/AD-425
**Checklist:**
=> [AD-425] Allow no accounts selection in send form

ariadne/cardano/src/Ariadne/MainTemplate.hs, stack.yaml
**Description:** Always run UI action in the main thread. This is needed to fix Qt on macOS. Also, "Timers can only be stopped from the main thread" message is gone :tada: 
**YT issue:** https://issues.serokell.io/issue/AD-428
**Checklist:**
=> [AD-428] Always run UI action in the main thread

knit/src/Knit/Eval.hs
**Description:** Replace `Union (:~:) a` with `ElemEv a`
**YT issue:** https://issues.serokell.io/issue/AD-408
**Checklist:**
=> [AD-408] Replace Union (:~:) a with ElemEv a

ariadne/cardano/test/Test/Ariadne/Knit.hs, knit/src/Knit/Autocompletion.hs, knit/src/Knit/DisplayError.hs, knit/src/Knit/FormattedExprExt.hs, knit/src/Knit/ParseTreeExt.hs, knit/src/Knit/Parser.hs, knit/src/Knit/Tokenizer.hs
Store space between the tokens as `String`s instead of `Span`s. This simplifies some parts of autocompletion and allows to store different kinds of unimportant characters between the tokens like tabs or comments.
**YT issue:** https://issues.serokell.io/issue/AD-456
**Checklist:**
=> [AD-456] Use String to store space between tokens

ui/qt-app/Glue.hs
**Description:** GUI sends password for new wallet as Maybe Text, where Nothing
represents "no password", while backend treated Nothing as "no password
information provided". Correct backend representation of "no password"
is "". This commit fixes it.
**YT issue:** https://issues.serokell.io/issue/AD-451
**Checklist:**
=> [AD-451] Fix double password request on new wallet

ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/core/src/Ariadne/UX/PasswordManager.hs
**Description:** 
Wallet backend needs to generate new address for change when sending TX. To do so it needs password for the wallet. When it requests password from password manager, request turns into `WalletIdTemporary` request and thus can't use previous password obtained by `WalletIdByUiIndex` request. This happens because `walletNewAddress` knows nothing about UI indices and `PasswordManager` knows nothing about `HdRootId`.
I made `PasswordManager` polymorphic over backend wallet id type and had to propagate a type variable through a lot of code.
On the second thought though, maybe it would be better to hide backend wallet id type behind some monomorphic data type and expose only that to UI, so that UI can't see what's in there, only backend and password manager can.
**YT issue:** …
=> [AD-455] Make PasswordManager store HdRootId

.stylish-haskell.yaml
**Description:** `stylish-haskell` doesn't work on
https://github.com/serokell/ariadne/blob/839815b5a42688995a771eb690309f50f6f56c8a/ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs#L7
without `PatternSynonyms`.
**YT issue:** ~~https://issues.serokell.io/issue/AD-~~
**Checklist:**
=> Add PatternSynonyms to .stylish-haskell

ariadne/cardano/test/Test/Ariadne/Knit.hs, knit/package.yaml, knit/src/Knit/Autocompletion.hs, knit/src/Knit/DisplayError.hs, knit/src/Knit/FormattedExprExt.hs, knit/src/Knit/ParseTreeExt.hs, knit/src/Knit/Parser.hs, knit/src/Knit/Tokenizer.hs, ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs
**Description:** Cursor is now stored inside the tree. This allows to use all of the input in the autocompletion (before only text before the cursor was parsed for autocompletion purposes) and has potential use cases for other editing features. On the other hand, it is quite hard to manipulate the tree with all that formatting info, and maybe something should be done about it.
**YT issue:** https://issues.serokell.io/issue/AD-458
**Checklist:**
=> Store cursor in the parse tree

ariadne/cardano/src/Ariadne/MainTemplate.hs, ui/qt-app/Glue.hs, ui/qt-app/Main.hs, ui/qt-lib/src/Ariadne/UI/Qt.hs, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/MainWindow.hs, ui/vty-app/Main.hs
**Description:** Backend exceptions couldn't be successfully handled by Qt app due to it's FFI calls. Now when exception on backed thread happens, it is being handled by custom link function, that finalize UI and rethrow this exception to UI thread.
To check this add something like `threadDelay 5000000 >> throwM (ExitFailure 42)` to [serviceAction](https://github.com/serokell/ariadne/blob/b21274c96038069f42293dacbe621c8e95432790/ariadne/cardano/src/Ariadne/MainTemplate.hs#L158)
**YT issue:** https://issues.serokell.io/issue/AD-432
**Checklist:**
=> [AD-432] Support custom finalizers for the UI

ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs
**Description:** Drop logic for creation of unique wallet name and set default wallet name to "Untitled wallet" within `addWallet` function
**YT issue:** https://issues.serokell.io/issue/AD-489
**Checklist:**
=> [AD-489] remove pwlGetDBSnapshot from addWallet

ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, ui/qt-app/Glue.hs, ui/vty-app/Glue.hs
**Description:** Replace confirmRemove constructors with two constructors: `ConfirmRemoveWallet WalletName` and `ConfirmRemoveAccount AccountName`.
**YT issue:** https://issues.serokell.io/issue/AD-491
**Checklist:**
=> [AD-491] remove DB from comfirmationType

ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Types.hs
**Description:** newWallet uses mnemonicToSeedNoPassword and safeDeterministicKeyGen. We should hide this logic behind PassiveWalletLayer.
**YT issue:** https://issues.serokell.io/issue/AD-496
**Checklist:**
=> [AD-496] Hide newWallet logic behind PassiveWalletLayer

ariadne/cardano/config/configuration.yaml, ariadne/cardano/src/Ariadne/Cardano/Backend.hs, ariadne/cardano/src/Ariadne/Cardano/Face.hs, ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Mode.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Addresses.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Bip32.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Derivation.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Internal.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/test/backend/Test/Infrastructure/Generator.hs, ariadne/cardano/test/backend/Test/Spec/Accounts.hs, ariadne/cardano/test/backend/Test/Spec/CreateAddress.hs, ariadne/cardano/test/backend/Test/Spec/CreateWallet.hs, ariadne/cardano/test/backend/Test/Spec/Fixture.hs, ariadne/cardano/test/backend/Test/Spec/Kernel.hs, ariadne/cardano/test/backend/UTxO/Context.hs, stack.yaml
cardano-sl in `ariadne` branch was bumped to 1.3.1.
See https://github.com/serokell/cardano-sl/pull/43
The most intrusive change is the addition of 'NetworkMagic'.
I had to swap the order of creation of Cardano and Wallet backends,
because Wallet backend creation now needs 'ProtocolMagic', which
is obtained from Cardano.
**YT issue:** https://issues.serokell.io/issue/AD-481
**Checklist:**
=> [AD-481] Use newer version of cardano-sl

.gitignore, ariadne/cardano/package.yaml, ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Mode.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Bip44.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet/Derivation.hs, ariadne/cardano/test/Spec.hs, ariadne/cardano/test/Test/Ariadne/Bip44.hs
Made 2 tests - test of bip44 path encoding and of address generation. 
Also added new field to the `Bip44DerivationPath` - bip44CoinType 
(also added new data type `HdCoinType` with one constuctor). 
That was done for debugging, but i decided to leave it. 
**YT issue:** https://issues.serokell.io/issue/AD-227
**Checklist:**
=> [AD-227] Add tests for BIP-44 derivation

docs/usage-gui.md, ui/qt-app/Glue.hs, ui/qt-lib/resources/stylesheet.qss, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/AccountSettings.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
**Description:** Dialog to rename or delete account
UX is a bit sad: to actually rename you need to either unfocus the edit widget (not possible since there are no other widgets) or press enter.
If you click "Delete account" and then cancel that dialog, account settings will close as well. Fixing that will require more `IORef` trickery and I don't suppose it's super important to do.
**YT issue:** https://issues.serokell.io/issue/AD-476
**Checklist:**
=> [AD-476] Add Account Settings dialog

README.md
Problem: build and usage instructions were outdated. Specifically:
1. Wrong list of supported platforms (GUI works on MacOS now).
2. Stack way no longer works on MacOS.
3. Nix way should preferred and listed first.
4. Instruction with `sudo` doesn't use `sudo` by default, because
presumably more people have single-user setup.
5. Usage instructions didn't mention that `ariadne-qt` has to be
launched from `nix-shell` if it's built using `nix-build`.
Solution: update build instructions and usage instructions.
**YT issue:** https://issues.serokell.io/issue/AD-435
**Checklist:**
=> [AD-435] Update build and usage instructions in README

ariadne/cardano/src/Ariadne/Cardano/Knit.hs, ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, ui/qt-app/Main.hs, ui/qt-lib/package.yaml, ui/qt-lib/resources/stylesheet.qss, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Send.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Util.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Validation.hs
Display validation errors for inputs in dialogs.
Known problems:
**YT issue:** https://issues.serokell.io/issue/AD-398
**Checklist:**
=> [AD-398] Display of validation errors in dialogs

ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/Tx.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/AcidState.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec/Update.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Internal.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Types.hs, ariadne/cardano/test/backend/Test/Infrastructure/Generator.hs, ariadne/cardano/test/backend/Test/Spec/Fixture.hs, ariadne/cardano/test/backend/Test/Spec/Kernel.hs, ariadne/cardano/test/backend/Wallet/Inductive/Cardano.hs
This is a duplicate of https://github.com/serokell/ariadne/pull/328, which was automatically closed upon merging https://github.com/serokell/ariadne/pull/321.
This PR reintroduces the `ActiveWallet` & `ActiveWalletLayer` and adds a call to `newPending` to `sendTx`. Design-wise, this goes the opposite way compared to the original implementation (the intent was to add a transaction to the submission layer after a successful call to `newPending`), but this is OK since semantics-wise we do the same thing: we first create a new transaction, then try calling `newPending`, and if the call fails, we propagate the exception without submitting the transaction.
The tests now also call `newPending`. This helped fix one of the two failing tests left after AD-167.
**YT issue:** …
=> [AD-369] Call newPending in sendTx

ariadne/cardano/src/Ariadne/Wallet/Backend/Restore.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, ariadne/cardano/src/Ariadne/Wallet/Knit.hs, docs/usage-gui.md, docs/usage-tui.md, ui/qt-app/Glue.hs, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/NewWallet.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletTree.hs, ui/vty-app/Glue.hs, ui/vty-app/Main.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs
Problem: It was decided to remove concept of not full restore.
Solution: Remove choose checkboxes and permofm full restore by default.
**YT issue:** https://issues.serokell.io/issue/AD-479
**Checklist:**
=> [AD-479] Remove full restore

ariadne/cardano/package.yaml, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/BlockMeta.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/HdWallet.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Spec.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/test/backend/Test/Spec/Accounts.hs, ariadne/cardano/test/backend/Test/Spec/AcidState.hs, ariadne/cardano/test/backend/Test/Spec/CreateWallet.hs, ariadne/cardano/test/backend/Test/Spec/Fixture.hs, ariadne/cardano/test/backend/WalletUnitTest.hs, stack.yaml
This PR fixes the bugs that were added in the  PR #350 due to the bug in acid-state: 
1. Ariadne failed to be started with an empty database.
2. `openLocalState` function loads not the current state of DB, but the previous one.
Also, it adds tests to check the behavior of the `acid-state` related functions. 
**YT issue:** https://issues.serokell.io/issue/AD-452
**Checklist:**
=> [AD-502] `getstate` function fails if there is an empty db

.github/pull_request_template.md
Problem: some links in PR template were broken, because GitHub uses
some weird rules for links in PR.
Solution: update the links by prefixing them with `../tree/master/`, because
empirically it turned out to work.
https://issues.serokell.io/issue/AD-509
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
=> [AD-509] Fix PR template

ariadne/cardano/test/Test/Ariadne/Knit.hs, knit/src/Knit/Autocompletion.hs, knit/src/Knit/FormattedExprExt.hs, knit/src/Knit/ParseTreeExt.hs, knit/src/Knit/Parser.hs, knit/src/Knit/Printer.hs, knit/src/Knit/Tokenizer.hs
**Description:** Allow partial parses of names and keys which end on '-'.
**YT issue:** https://issues.serokell.io/issue/AD-487
**Checklist:**
=> [AD-487] Allow partial parses of names and keys

pkgs.nix
Bump closure pin after bumping nixpkgs after bumping all-cabal-hashes.
https://issues.serokell.io/issue/OPS-667
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
=> [OPS-667] Bump closure pin to update all-cabal-hashes

Makefile, ariadne/cardano/src/Ariadne/Config/Ariadne.hs, ariadne/cardano/src/Ariadne/Config/CLI.hs, ariadne/cardano/src/Ariadne/Config/Logging.hs, ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/test/Spec.hs, ariadne/cardano/test/Test/Ariadne/Logging/Arbitrary.hs, ariadne/core/package.yaml, ariadne/core/src/Ariadne/Logging.hs, ariadne/core/test/Spec.hs, ariadne/core/test/Test/Ariadne/Logging.hs, config/ariadne-config.dhall, config/cardano.dhall, config/logging.dhall, config/update.dhall, config/wallet.dhall, docs/configuration.md, stack.yaml
Problem: it's not clear what one should do when they want to log something from Ariadne code. One approach is to use log-warper's functions, because log-warper is used by cardano-sl. However, it's not clear from the code that it should be used.
Moreover, I think using log-warper is not the best idea (see below).
We can't just use `putStrLn`, because it will break TUI. Also it would be good to print additional data with each message. `writeFile` won't break TUI, but it's not clear to which file one should log.
Solution: add `Ariadne.Logging` module with a simple `co-log`-based logging implementation to `ariadne-core`.
Current logging behavior is quite simple: each message is logged into a file called `ariadne.log`, location of this file is configurable.
It would be good to also put …
=> [AD-519] Add proper logging

ariadne/cardano/package.yaml, ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Consistency.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/DB/Util/IxSet.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Keystore.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Wallets.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Kernel.hs, ariadne/cardano/src/Ariadne/Wallet/Cardano/WalletLayer/Types.hs, ariadne/cardano/src/Ariadne/Wallet/Face.hs, ariadne/core/src/Ariadne/UIConfig.hs, ui/qt-app/Glue.hs, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Delete.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/Dialogs/Util.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletTree.hs, ui/vty-app/Glue.hs, ui/vty-lib/src/Ariadne/UI/Vty/App.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmMnemonic.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmRemove.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmSend.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/Utils.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Checkbox.hs
**YT issue:** https://issues.serokell.io/issue/AD-270
**Checklist:**
> It's possible that key file has more secret keys than there are wallets in wallet DB. Btw, the opposite is impossible. 
So - now unknown keys are deleted on startup.
=> [AD-270] Check keyfile for unknown keys on startup

ariadne/cardano/src/Ariadne/MainTemplate.hs, ariadne/cardano/src/Ariadne/Wallet/Backend.hs, ariadne/cardano/src/Ariadne/Wallet/Backend/KeyStorage.hs, ariadne/core/package.yaml, ariadne/core/src/Ariadne/Logging.hs, ui/qt-app/Main.hs, ui/vty-app/Main.hs, ui/vty-lib/package.yaml, ui/vty-lib/src/Ariadne/UI/Vty.hs, ui/vty-lib/src/Ariadne/UI/Vty/App.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Account.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/AddWallet.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmMnemonic.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmRemove.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmSend.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/Password.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Checkbox.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Edit.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/List.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Form/Send.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Logs.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Menu.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Repl.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Status.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Tree.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Wallet.hs
This PR contains the first set of changes I made while working on AD-445. The bug happens because the UI thread in some cases calls `putUiEvent` which can block and the UI thread is the only one which can unblock it. More details can be found in the issue comments. It's recommended to review this PR on per-commit basis. Contents:
1. Some changes related to logging which I made to facilitate debugging. 
2. One place where `putUiEvent` can be called from the UI thread has been reworked, so that now it's impossible.
3. Refactored TUI code to make it more understandable by eliminating one `StateT` layer (see the corresponding commit description).
Note: there will be at least one more PR, I just want to avoid too large PRs.
https://issues.serokell.io/issue/AD-445
- Tests
silently reappearing …
=> [AD-445] Add logging, fix one issue, refactor vty code

docs/usage-gui.md, ui/qt-app/Glue.hs, ui/qt-lib/src/Ariadne/UI/Qt/Face.hs, ui/qt-lib/src/Ariadne/UI/Qt/Widgets/WalletInfo.hs
Problem: VTY UI displays wallet ids (HdRootId), that can be usable as
stable identifiers in some knit commands, more convenient than UI
indices. QT UI does not display them.
Solution: Make QT UI display wallet ids as tooltips on wallet names.
**YT issue:** https://issues.serokell.io/issue/AD-486
**Checklist:**
=> [AD-486] Display wallet id in GUI

ui/vty-lib/src/Ariadne/UI/Vty.hs, ui/vty-lib/src/Ariadne/UI/Vty/App.hs, ui/vty-lib/src/Ariadne/UI/Vty/Face.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmMnemonic.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmRemove.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/ConfirmSend.hs, ui/vty-lib/src/Ariadne/UI/Vty/Widget/Dialog/Password.hs
Problem: sometimes vty app can go into modal mode and some widgets use
`putUiEvent` to let the app know that it should exit modal mode. They do it
from the UI thread and because of that `putUiEvent` can block forever.
Solution: add a new event to `WidgetEvent` to disable modality and send this
event to parent using `widgetEvent`.
https://issues.serokell.io/issue/AD-445
- Tests
- Haddock
of Public …
=> [AD-445] Do not use UiFace to disable modality

ariadne/cardano/src/Ariadne/Wallet/Cardano/Kernel/Restore.hs, stack.yaml
Problem: some changes have been made to `cardano-sl`, see
https://github.com/serokell/cardano-sl/pull/46.
Solution: update `cardano-sl` to the latest version.
https://issues.serokell.io/issue/AD-512
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
=> [AD-512] Update cardano-sl due to reverted UserSecret changes

ariadne/core/src/Ariadne/Knit/Backend.hs, ariadne/core/src/Ariadne/Knit/Face.hs, ui/qt-app/Glue.hs, ui/vty-app/Glue.hs
Problem: `langPutUiCommand` is executed from the UI thread and it calls
`putUiEvent` which can block and only the UI thread can unblock it. So deadlock is possible.
Solution: call `putUiEvent` from Knit backend, inside action passed to
`spawnTask`. That action is executed from non-UI thread, so it can't deadlock.
One alternative would be to introduce a way to send an event from widgets to
REPL. However, that seems to be too hard.
Another alternative is to fork a thread specifically for `putUiEvent`, but
this event should be processed before the command is executed, because
otherwise `updateCommandResult` will ignore all events related to this command.
This problem was present before, because `putUiEvent` was called after
`putCommand`.
This approach is quite simple and doesn't require …
=> [AD-445] Do not send command to REPL from UI thread

docs/usage-tui.md
Problem: some Knit commands have `no-confirm` boolean option, but it's
not documented, making it essentially hidden from users.
Solution: mention this option in `usage-tui.md`. Since `usage-gui.md`
references TUI doc for knit-related information, it was not updated.
https://issues.serokell.io/issue/AD-494
- Tests
- Haddock
of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) …
=> [AD-494] Mention `no-confirm` in usage doc
